profile/README.md
profile/README.rst

Rename and update readme

---

.github/workflows/global-replicator.yml

fix replicator matrix

---

.github/workflows/global-replicator.yml

fix replicator secrets

---

.github/workflows/global-replicator.yml

- fix replicator max parallel
- fix replicator branch (uses regex and was catching dependabot or other branches that contained "nightly")

fix replicator max parallel

---

.github/workflows/automerge.yml

only automerge on nightly

---

.github/workflows/issues-stale.yml

stale pr check based on label only

stale pr check based on label only

---

actions/create_release/action.yml
actions/verify_changelog/action.yml

- add verify_changelog action
- add create_release action

Add reusable actions

---

.github/workflows/automerge.yml

- fix automerge triggers
- Fixes #24

Change trigger events

---

.github/pr_release_template.md
.github/workflows/auto-create-pr.yml

- auto create pr (into `master` when `nightly` has a PR merged)

auto create pr

---

.github/pr_release_template.md
.github/pull_request_template.md

- Remove double quotes from pr templates

Remove double quotes

---

.github/workflows/automerge.yml
.github/workflows/autoupdate.yml
.github/workflows/global-replicator.yml

Add workflow that auto updates PRs from @LizardByte-bot

add autoupdate workflow

---

.github/workflows_extra/ci-docker.yml

- fix read `.docker_platforms` file

fix read `.docker_platforms` file

---

.github/workflows/automerge.yml

- add job needs to automerge workflow

add job needs to automerge workflow

---

.github/workflows/ci-docker.yml
.github/workflows/cpp-clang-format-lint.yml
.github/workflows/global-replicator.yml

- Update prechecks for docker and cpp
- Move `ci-docker` workflow
- This change should allow dependabot to check the `ci-docker` workflow

Update prechecks for docker and cpp

---

.github/workflows/automerge.yml

- Use GITHUB_TOKEN instead of personal token
- Cannot use token from same account that created the PR

Use GITHUB_TOKEN instead of personal token

---

.github/workflows/auto-create-pr.yml

- fix trigger for auto pr workflow

fix trigger for auto pr

---

.github/workflows/global-replicator.yml

fix docker workflow path

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/dependabot.yml
.github/label-actions.yml
.github/workflows/auto-create-pr.yml
.github/workflows/automerge.yml
.github/workflows/autoupdate.yml
.github/workflows/ci-docker.yml
.github/workflows/cla-gist-replicator.yml
.github/workflows/cpp-clang-format-lint.yml
.github/workflows/global-replicator.yml
.github/workflows/issues-stale.yml
.github/workflows/issues.yml
.github/workflows/pull-requests.yml
.github/workflows/python-flake8.yml
.github/workflows/release-notifier.yml
.github/workflows/yaml-lint.yml
.readthedocs.yaml
actions/create_release/action.yml
actions/verify_changelog/action.yml

add yaml-lint

---

.github/workflows/ci-docker.yml
.github/workflows/cpp-clang-format-lint.yml

- fix init checks (docker and cpp)

fix init checks

---

.github/workflows/ci-docker.yml
.github/workflows/cpp-clang-format-lint.yml

fix workflow if statements

---

.github/workflows/ci-docker.yml

add dockerfile lint

---

.github/workflows/global-replicator.yml

fix cpp workflow location

---

.github/dependabot.yml

- fix docker dependabot syntax error

fix docker dependabot

---

.github/workflows/ci-docker.yml

add `BUILD_VERSION` build arg

---

profile/README.rst

add patron count

---

.clang-format
.github/workflows/yaml-lint.yml

- add additional files to yamllint
- Fixes #70

add additional files to yamllint

---

.github/workflows/automerge.yml

- Dependency update... Why didn't @dependabot take care of this?

Bump hmarr/auto-approve-action from 2 to 3

---

.github/workflows/ci-docker.yml

- add ignore rules for hadolint action
- Resolves #97

add ignore rules for hadolint action

---

.github/workflows/ci-docker.yml

- fix dockerfile hadolint logs

fix dockerfile hadolint logs

---

README.rst
docs/requirements.txt
docs/source/about/donate.rst
docs/source/about/support.rst
docs/source/conf.py
docs/source/developers/automations.rst
docs/source/developers/contributing.rst
docs/source/index.rst
docs/source/version.py

change docs theme to `furo`

---

profile/README.rst

fix discord link

---

.github/workflows/global-replicator.yml

- add dependabot-rebase
- reformat `patterns_to_include` keys

update global replicator

---

.github/workflows/autoupdate.yml

Fixes condition for dependabot rebase action.

fix condition for dependabot rebase

---

.github/workflows/cpp-lint.yml
.github/workflows/global-replicator.yml

- add cmake lint action
- rename `cpp-clang-format-lint.yml` to `cpp-lint.yml`

add cmake lint

---

.github/workflows/ci-docker.yml

- adds two step build, so artifacts can be extracted before the final stage
- adds custom directives, `platforms` and `artifacts` to dockerfiles as comments... the values will determine which platforms to run for that image, and whether to pull artifacts or not
- use a matrix build for dockerfiles so can have multiple dockerfiles for a repository
Tested:
- https://github.com/LizardByte/Sunshine/pull/714
- https://github.com/LizardByte/RetroArcher/pull/190
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-cre …

update docker workflow

---

.github/dependabot.yml

Add `nuget` to dependabot to support `Themerr-jellyfin`.

dependabot: add nuget

---

.github/workflows/global-replicator.yml

Exclude forked repos for global replicator.

ci: exclude forked for replicate

---

.github/workflows/ci-docker.yml

- add no cache filters
- add clone url and release build args
- remove `provenance.json` file from artifacts
This PR will replace #193 

docker: add no-cache-filters

---

docs/source/_static/js/projects.js
docs/source/conf.py

- Add projects list to docs using custom javascript.

docs: add projects list

---

docs/source/conf.py

docs: add favicon

---

.github/workflows/ci-qodana.yml
.github/workflows/global-replicator.yml

Add qodana workflow. Workflow checks for qodana config files, and if not found will not run further jobs. `qodana-<language>.yaml` must exist in the target repo, it will not be copied from this `.github` repo.

replicator: add qodana

---

.github/workflows/ci-qodana.yml

Use repository dispatch for qodana.

qodana: use repository dispatch

---

.github/workflows/ci-qodana.yml
.github/workflows/dispatch-issue-comment.yml

- refactors qodana workflow
- adds issue/pr comment dispatch workflow

qodana: refactor workflow

---

.github/workflows/dispatch-issue-comment.yml

Use workflow dispatch for issue comment. This resolves an issue where the workflow must exist on the default branch.
Also, this PR is testing the ability to comment on issues/PRs in another repo.

Use workflow dispatch for issue-comment

---

.clang-format

This PR will allow clang-format to adjust comments.

style: adjust clang format rules for comments

---

actions/setup_python2/action.yml

GitHub has removed Python 2.7 from runners (https://github.com/actions/setup-python/issues/672), but we still need it for Plex plugins.

feat(actions): add setup python2.7 action

---

.github/workflows/codeql.yml
.github/workflows/global-replicator.yml

ci: add codeql analysis

---

.github/workflows/dispatch-issue-comment.yml

Use upstream repo for issue comment, since https://github.com/mshick/add-pr-comment/pull/78 is merged now.

fix(issue-comment): use upstream repo

---

profile/README.rst

Use cached data for discord badge.

docs: use cached data for discord badge

---

.readthedocs.yaml
.rstcheck.cfg
README.rst
docs/requirements.txt
docs/source/about/support.rst
profile/README.rst

Fix rtd build, and lint rst files.

docs: lint rst files and fix rtd build

---

profile/README.rst

Adds additional "pins" (light and dark mode), and modifies social badges.

docs: update profile

---

profile/README.rst

docs: fix themerrdb url

---

.github/DISCUSSION_TEMPLATE/actions.yml
.github/DISCUSSION_TEMPLATE/gsms.yml
.github/DISCUSSION_TEMPLATE/plexhints.yml
.github/DISCUSSION_TEMPLATE/plexyglass.yml
.github/DISCUSSION_TEMPLATE/plugger.yml
.github/DISCUSSION_TEMPLATE/python-plexapi-backport.yml
.github/DISCUSSION_TEMPLATE/retroarcher.yml
.github/DISCUSSION_TEMPLATE/sunshine.yml
.github/DISCUSSION_TEMPLATE/themerr.yml

This PR adds discussion templates for the org level discussions. I references the official GitHub community templates to create these.

feat: add discussion templates

---

.github/DISCUSSION_TEMPLATE/actions.yml
.github/DISCUSSION_TEMPLATE/gsms.yml
.github/DISCUSSION_TEMPLATE/plexhints.yml
.github/DISCUSSION_TEMPLATE/plexyglass.yml
.github/DISCUSSION_TEMPLATE/plugger.yml
.github/DISCUSSION_TEMPLATE/python-plexapi-backport.yml
.github/DISCUSSION_TEMPLATE/retroarcher.yml
.github/DISCUSSION_TEMPLATE/sunshine.yml
.github/DISCUSSION_TEMPLATE/themerr.yml
.github/ISSUE_TEMPLATE/bug-report.yml

This PR fixes multi-line template strings.

fix(templates): fix multiline template strings

---

.github/DISCUSSION_TEMPLATE/actions.yml
.github/DISCUSSION_TEMPLATE/gsms.yml
.github/DISCUSSION_TEMPLATE/plexhints.yml
.github/DISCUSSION_TEMPLATE/plexyglass.yml
.github/DISCUSSION_TEMPLATE/plugger.yml
.github/DISCUSSION_TEMPLATE/python-plexapi-backport.yml
.github/DISCUSSION_TEMPLATE/retroarcher.yml
.github/DISCUSSION_TEMPLATE/sunshine.yml
.github/DISCUSSION_TEMPLATE/themerr.yml
.github/ISSUE_TEMPLATE/bug-report.yml

Further adjustments to multi-line strings in templates.

style(templates): adjust multiline strings in templates

---

.github/workflows/issues-stale.yml

This PR removes the attempted mention of issue/pr authors, as this does not work for this action.

fix(stale-issues): remove attempted mention of issue author

---

.github/workflows/release-notifier.yml

This PR fixes the twitter notification job, as well as the conditions for the notification. i.e. the notification will only be sent if the release is NOT a pre-release.

fix(release-notifier): fix twitter job and conditions

---

.github/workflows/codeql.yml

This PR makes it so `dotnet` is not removed for csharp CodeQl analysis.

ci(codeql): improve logic for maximize build space

---

.github/workflows/release-notifier.yml

Fix workflow syntax for release notifications workflow.

ci: fix release notification conditions

---

renovate-config.json5

Change action term on renovate from "Update" to "Bump", to be more similar to dependabot.

fix(renovate): modify action term

---

.github/workflows/renovate-config-validator.yml
renovate-config.json5

Validate renovate config files in CI.

ci(renovate): validate configs

---

renovate-config.json5

chore: use loose versioning for LizardByte packages

---

.github/workflows/release-notifier.yml

This PR fixes the conditions in the release notifier workflow.

fix(ci): fix release notifier conditions

---

README.rst

The graph provided by the awesome-crowdin badges plugin intermittently fails, therefore this PR uses our own custom image, generated daily.

docs: use custom crowdin graph

---

renovate-config.json5

Add dependency groups for Renovate.

feat(renovate): add dependency groups

---

renovate-config.json5

Group plexapi and the plexapi-backport.

feat(renovate): group plexapi and plexapi-backport

---

profile/README.rst

docs(profile): add Themerr-kodi

---

.github/workflows/patch_missing_releases.yml

- Properly handle pagination
- Add logging

fix(patch releases): update workflow

---

.github/workflows/codeql.yml

Update based on https://github.com/LizardByte/Sunshine/pull/2425

ci: use matrix for cpp code ql analysis

---

profile/README.rst

Fixes some formatting issues in the org profile readme.

docs: fix readme formatting

---

.github/workflows/codeql.yml

Changes based on https://github.com/LizardByte/Sunshine/pull/2475

fix(codeql): use macos-13 and modify maximize build space

---

.github/workflows/global-replicator.yml
.github/workflows/update-changelog.yml

Adds new update changelog workflow.

feat: add update changelog workflow

---

.github/workflows/codeql.yml

Adds common ignore paths to codeql.

fix(codeql): add ignore paths

---

.github/workflows/codeql.yml

config ignore paths don't work for c++, so use https://github.com/advanced-security/filter-sarif
Testing here: https://github.com/LizardByte/Sunshine/pull/2597

fix(codeql): add sarif filter

---

.github/workflows/ci-docker.yml

Bump setup and create release actions, and provide new output and inputs.

build(deps): bump LizardByte release actions

---

.github/workflows/release-notifier.yml

- Simplify the release body, by removing the `Contributors` section, which does not display well on Reddit, and probably Discord. https://www.reddit.com/r/LizardByte/comments/1e5wf1t/comment/ldotmdb
- Update twitter secrets to use `X_`, and re-generated keys/secrets.
- Change discord side color to green.
- Add URL to discord title.
- Remove release body from facebook announcements.

fix(release_notifier): various fixes

---

renovate-config.json5

fix(renovate): update renovate config

---

.github/workflows/release-notifier.yml

The quotes can affect how the variable is written to the file.

fix(release_notifier): quote release body

---

.github/workflows/social-post.yml

fix(social): update x posts

---

.github/semantic.yml
.github/workflows/global-replicator.yml

This PR adds the config for semantic pr checking. The config must be merged into the default branches before we can install/enable the app.

feat: add semantic pr config

---

profile/README.md

Add awesome-sunshine to profile.

docs(profile): add awesome-sunshine

---

profile/README.md

fix(profile): use div instead of p

---

CONTRIBUTING.md

Add forks to CLA exemption list.

docs: update cla exemptions

---

.github/workflows/release-notifier-test.yml
.github/workflows/release-notifier.yml

Fix and test the release notifier script.

ci(releases): fix release notifier

---

docs/source/about/donate.rst

docs(donate): update patreon data

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/global-replicator.yml

Update global issue template config and use it for all repos.

fix: update issue template

---

.github/dependabot.yml

Add dependency groups. Mostly this is for `shared-web` and npm development deps, but it should reduce PRs in other scenarios as well.

feat(dependabot): add groups

---

.github/workflows/global-replicator.yml

Partially revert https://github.com/LizardByte/.github/pull/394

fix(issues): replicate issue template config to repos with custom issues

---

CONTRIBUTING.md

docs(contributing): add note about sonarlint

---

.github/FUNDING.yml
docs/source/about/donate.rst
profile/README.md

No longer accepting donations through mee6.

chore: remove mee6

---

profile/README.md

Add facebook-post-action to profile and alphabetize actions.

docs(profile): add facebook-post-action

---

profile/README.md

docs(profile): remove facebook group

---

.github/workflows/ci-docker.yml

Something changed with how artifacts are extracted from the docker builds. This fixes that.
See https://github.com/LizardByte/Sunshine/pull/3472

ci(docker): fix docker artifacts

---

profile/README.md

- Add upptime badges
- Add logo to website badge
- Add developer href
- Add emojis to headings

docs(profile): update badges

---

cla/CLA
cla/CLA-entity

Updates the contributing URL. Additionally, whitespace has been automatically removed.

docs(cla): update contributing url

---

SECURITY.md

docs(github): add security policy

---

.github/workflows/release-notifier.yml

Adds missing front matter variable and corrects directory of blog post file.
- Fixes #420

fix(release-notifier): multiple fixes

---

.github/workflows/update-docs.yml

The latest version was not automatically rebuilt after the last Sunshine stable release. This should fix that.

fix(rtd): trigger a new build automatically

---

.github/workflows/social-post.yml

No longer using secret for org logo url.

ci(social-post): use org variable for discord avatar url

---

.github/workflows/social-post.yml

Use org level variable for discord embed.

ci(social-post): use variable for discord color

---

.github/ISSUE_TEMPLATE/config.yml

Separate discussions into 3 categories even though they all go to the same URL.

chore(issues): make discussion categories more obvious

---

.github/workflows/ci-docker.yml

Dependency updates missed because of https://github.com/LizardByte/.github/issues/414 as well as rolling back the runner image to ubuntu-22.04.

ci(docker): update workflow

---

SECURITY.md

Reverts LizardByte/.github#429

revert: "docs(security): add href for security tab"

---

profile/README.md

Fixes extra whitespace in html badges.

docs(profile): fix badge whitespace

---

docs/source/about/donate.rst
profile/README.md

Add sponsors image to profile.

docs(profile): add sponsors

---

docs/source/_static/js/projects.js
docs/source/conf.py

This PR labels archived projects and adds them at the end of the list.

docs(rtd): separate active from archived projects

---

CONTRIBUTING.md
profile/README.md

- Add localization guidelines
- Update sponsors image url in profile

docs(contributing): add localization guidelines

---

docs/source/about/donate.rst
docs/source/version.py

`version.py` file is unused. Additionally, updates the sponsors image url on the donate page.

docs(sphinx): remove unused `version.py`

---

CONTRIBUTING.md
README.rst

See https://github.com/LizardByte/contributors/pull/13

docs(crowdin): add crowdin contributors graph

---

.github/workflows/ci-docker.yml
.github/workflows/codeql.yml
.github/workflows/common-lint.yml
.github/workflows/global-replicator.yml
.github/workflows/issues-stale.yml
.github/workflows/issues.yml
.github/workflows/release-notifier.yml
.github/workflows/renovate-config-validator.yml
.github/workflows/update-changelog.yml
.github/workflows/update-docs.yml
.github/workflows/update-flathub-repo.yml
.github/workflows/update-homebrew-release.yml
.github/workflows/update-pacman-repo.yml
.github/workflows/update-winget-release.yml

Add 4 package release workflows, from Sunshine.
- update flathub repo
- update homebrew release
- update pacman repo
- update winget release
Additionally, make any global workflows that upload artifacts fail (instead of warn) if no artifacts are found.

feat(global-workflows): add package release workflows

---

.github/workflows/codeql.yml

When analyzing c++ the results are uploaded multiple times per OS to the same category. This can result is inconsistent behavior.

ci(codeql): fix categories for multi os languages

---

README.rst

docs(readme): center images

---

.github/workflows/common-lint.yml

This PR adds linting for PowerShell.

feat(lint): add powershell linting

---

CODE_OF_CONDUCT.md

Add contact method to code of conduct.

docs(code_of_conduct): add contact method

---

.github/workflows/update-flathub-repo.yml

Changes based on https://github.com/LizardByte/Sunshine/pull/3954

fix(flathub): improve changelog generation

---

.github/workflows/__call-update-flathub-repo.yml
.github/workflows/__call-update-homebrew-repo.yml
.github/workflows/__call-update-pacman-repo.yml

Several fixes discovered after Sunshine release v2025.628.4510
- Flathub repo does not allow auto merge
- Homebrew workflow had competing concurrency rules
- Pacman workflow tried to delete the wrong file

fix(workflows): fix release workflows

---

.github/workflows/__call-docker.yml

`BUILD_VERSION` should be a strict version number without `v` prefix. This is necessary for https://github.com/LizardByte/Sunshine/pull/4037

fix(docker)!: add release_version input

---

.github/workflows/__call-codeql.yml

This PR adds rust support for CodeQL.
- Closes https://github.com/LizardByte/roadmap/issues/94

feat(codeql): add rust analysis

---

.github/workflows/__issues-stale.yml

The stale workflow added stale to a roadmap entry. We should prevent this as everything on the roadmap should be left open. We can accomplish this by exempting the `planned` label.

ci(stale): exempt `planned` issues from becoming stale

---

.github/workflows/__update-cpm-cmake.yml

fix(update-cpm): add repo owner to checkout step

---

.github/workflows/__update-cpm-cmake.yml

Incorrect token secret was used.

fix(update-cpm): use correct token

---

.github/workflows/__call-docker.yml

This PR makes the `root_reserve_size` adjustable for the `maximize_build_space` action.

ci(docker): adjustable free space

---

.github/workflows/__call-common-lint.yml

When using git to get a list of PR changed files has a couple of issues.
1. must get more history during checkout
2. if PR branch is not up to date, it will fail to get a list of changed files

fix(lint): get changed files via rest API

---

.github/workflows/__call-common-lint.yml

Skipping checking eol on binary files, such as images.

fix(lint): do not check-eol on binary files

---

docs/source/community/community_rules.md
docs/source/community/community_rules.rst
docs/source/conf.py
docs/source/developers/code_of_conduct.md
docs/source/developers/code_of_conduct.rst
docs/source/developers/contributing.md
docs/source/developers/contributing.rst

Fix for GitHub style admonitions in markdown files. See https://github.com/executablebooks/MyST-Parser/issues/845

docs: render github admonitions in markdown files
