.github/workflows/global-replicator.yml
- set max-parallel to 1 for global-replicator workflow
- The workflow can fail to create PRs when running too many jobs in parallel
=> global-replicator - set max-parallel to 1

.github/workflows/autoupdate-labeler.yml
This PR should fix the autoupdate labeler. The variables for the `contains` expression were reversed according to https://docs.github.com/en/actions/learn-github-actions/expressions#contains
=> correct `contains` expression

.github/workflows/autoupdate-labeler.yml
Use `fromJson` expression to correct issue with `\r` and `\n` in workflow. See https://stackoverflow.com/questions/72277477/how-to-use-escape-sequences-in-strings-in-github-actions-expressions for more details.
=> use `fromJson` expression

.github/workflows/global-replicator.yml
- replicate global workflows to forked repos (excluding specific repos)
- This is required to better maintain the `archlinux-package-action` locally.
- Only forked repos with a `nightly` branch will get replicated files.
=> replicate global workflows to forked repos

.github/workflows/autoupdate.yml
do not rebase dependabot PRs labeled as `central_dependency`
=> fix dependabot rebase conditions

.github/workflows/autoupdate-labeler.yml, .github/workflows/autoupdate.yml
- change to `pull_request_target` trigger so the action can run without approval
- label is now added when a PR is approved by an organization member
- label is now removed when PR is synchronized and actor is not an organization member
- for organization members, the label is added/removed on additional events, such as editing the PR body (e.g. checking or unchecking a checkbox).
=> fix autoupdate labeler for forks

.github/workflows/autoupdate-labeler.yml
unlabel if anyone unchecks the box in the PR body, currently limited to org members
=> fix unlabel autoupdate conditions

.github/workflows/autoupdate-labeler.yml
This PR "fixes" autoupdate label events. Cannot use `pull_request_review` as it doesn't have access to secrets when a review is made by an outside member.
- Closes #148 
=> fix autoupdate label events

.github/workflows/autoupdate.yml
The github context to check for the `central_dependency` label runs in the context of the push, unfortunately not in the context of the dependabot PR.
=> remove dependabot rebsae condition

.github/workflows/python-flake8.yml
flake8 v6.0.0 removed support for type comments which are required for Python 2.7 type hints. This is a temporary fix to allow workflows to continue working until an alternate solution is found.
- Resolves #131 
=> pin flake8 version

.github/workflows/pull-requests.yml
- using concurrency on `pull_request_target` will fail workflows from other PRs
=> fix pull request workflow

.github/workflows/ci-docker.yml
Docker build dependent on event type. This can alleviate issues with slow builds for arm64 on PR events.
=> docker build dependent on event type

.github/workflows/autoupdate.yml
- Disable dependabot auto rebase
Disabled due to:
- no major version tag, resulting in constant nagging to update this action (https://github.com/bbeesley/gha-auto-dependabot-rebase/issues/262)
- additionally, the code is sketchy, 16k+ lines of code? (https://github.com/bbeesley/gha-auto-dependabot-rebase/blob/main/dist/main.cjs)
=> disable dependabot auto rebase

.github/workflows/ci-docker.yml
Docker artifact name was set to use `sunshine` as a prefix. This has been changed to `Docker`.
=> ci: docker: update artifact names

.github/workflows/global-replicator.yml
Re-enable on push event for global replicator.
Note: Only files that were changed in the commit will be replicated to other repos.
=> ci: replicate on push

.github/workflows/ci-qodana.yml, .github/workflows/dispatcher.yml, .github/workflows/global-replicator.yml
Use workflow dispatch for qodana. This solves some issues with access tokens/secrets for PRs from forks.
Also adds a new `dispatcher.yml` workflow to pass through a dispatch event to another repo.
=> qodana: use workflow dispatch

.github/workflows/cpp-lint.yml
This PR adds the ability to ignore specified directories for clang format.
=> style(clang-format): add option to ignore directories

.github/workflows/ci-docker.yml
This PR increases the runner size for docker builds. In some cases docker builds were failing, especially when attempting to build multiple architectures for Sunshine.
=> build(docker): free additional space on runners

.github/workflows/cpp-lint.yml
Bump DoozyX/clang-format-lint-action from v0.16 to v0.16.2, fixing a permissions issue.
=> build(deps): bump DoozyX/clang-format-lint-action from v0.16 to v0.16.2

.github/workflows/codeql.yml
Properly detect C++ and C# languages, by remapping them to the CodeQL equivalent of `cpp` and `csharp`. Additionally:
- adds prebuild mechanism for when autobuild fails
- adds workflow concurrency
- fixes issue with javascript variable
=> fix(codeql): detect cpp and csharp

actions/setup_python2/action.yml
Put Windows style path on PATH environment for Windows OS.
=> fix: use Windows style PATH for Python 2.7

.github/dependabot.yml
Before merging this, I need to update the default branch on nearly all repos in the org.
=> ci: use default branch for dependabot

.github/workflows/global-replicator.yml
When using max-parallel = 1, all the runners in the org are quickly consumed and we cannot update the PR branches fast enough... resulted in a lot of wasted runner minutes and time before it will continue in the matrix.
This change ensures all matrix jobs are started and the pushes will continue to happen.
=> ci(replicator): use wait-for-jobs instead of max-parallel

.github/workflows/codeql.yml
Maximize build space for CodeQL. This should fix an issue in Sunshine, where the runner is randomly running out of space (likely due to Cuda).
See: https://github.com/LizardByte/Sunshine/pull/1714
=> ci(codeql): maximize build space

renovate-config.json, renovate-config.json5
This PR adds a reusable config for [renovate](https://docs.renovatebot.com).
=> feat: add renovate config

renovate-config.json5
Add constraint filtering to renovate config, which "should" ensure dependencies match the python version in the requirements files.
=> fix(renovate): add constraint filtering

renovate-config.json5
Add package rules for LizardByte's GitHub actions, and allow renovate to update to "unstable" versions, since our tags do not match the standard.
=> fix(renovate): set packageRules for LizardByte actions

README.rst, docs/source/_static/css/crowdin-furo.css, docs/source/_static/js/crowdin.js, docs/source/_static/js/crowdin_web_widget.js, docs/source/conf.py
Add language switcher and in site translation tool
=> docs: add language switcher

.github/workflows/global-replicator.yml
After merging, this will remove qodana config files from LizardByte repos.
=> fix: remove qodana config files

.github/workflows/global-replicator.yml
Since PRs take the first commit as the PR title, this PR adjusts the global replicator to use the same commit message for each job in the matrix.
=> fix(global-replicator): use commit message

CONTRIBUTING.rst
=> docs: remove qodana guidelines

.github/workflows/patch_missing_releases.yml
This PR adds a workflow that needs to be run manually. The purpose is to perform an "edit" with no actual changes on each release in the organization.
- Fixes #311 
=> feat(workflows): add workflow to patch missing releases

.github/workflows/patch_missing_releases.yml
Skip releases that don't actually exist.
=> fix(patch-releases): skip non existent releases

.github/workflows/global-replicator.yml
Use a single job to replicate files instead of a matrix. The matrix caused an issue when waiting for open runners as they could not complete fast enough.
=> refactor: use single job for global replicator

.github/workflows/global-replicator.yml
This is not necessary to have in every repo in the org.
=> fix: only replicate update-changelog to release notification repos

.github/workflows/ci-docker.yml
This PR moves the docker ci to use the new setup release and create release actions. This will enable more of a "rolling" release model.
This will require testing before merging. Candidates for testing are "discord-bot" or "reddit-bot" repos.
- #297 
- #310 
- #315 
=> ci(docker): use new LizardByte release methodolgy

.github/workflows/release-notifier.yml
Now that all repos are on pre-release logic, we can fix the release notifier to only send updates when a stable release is published. Editing from pre-release to non pre-release should trigger this workflow.
This hasn't run in a while, so it's unknown which ones still work... but in any event, this should be an improvement.
=> fix: use correct logic in release notifier

.github/workflows/codeql.yml
Use ucrt64 for codeql build when using msys2.
See: https://github.com/LizardByte/Sunshine/pull/2580
=> fix(codeql): use ucrt64 for msys2

.github/workflows/global-replicator.yml
Don't exclude all forks by default. The list of excluded repos is now an env variable that will need to be udpated if/when new forks are added.
=> fix(global-replicator): don't exlude all forks

.github/workflows/global-replicator.yml, .github/workflows/update-docs.yml
Add a readthedocs updater workflow.
=> feat(docs): add readthedocs updater

.github/workflows/codeql.yml
Sunshine now fetches some third-party dependencies during the build process which are stored in `build`. These need to be ignored in code-ql.
=> feat(codeql): ignore build directory

.github/workflows/release-notifier.yml
Use a heredoc to ensure the simplified changelog body is able to be set as an output.
=> fix(release_notifier): ensure github output can take multline strings

.github/workflows/social-post.yml
Add ability to post to social platforms from GitHub.
=> feat: add social post workflow

.github/ISSUE_TEMPLATE/config.yml, .github/dependabot.yml, .github/label-actions.yml, .github/pull_request_template.md, .github/workflows/global-replicator.yml, .github/workflows/issues-stale.yml
Run stale issues workflow under a matrix. This PR will remove that workflow from every individual repo in the org, and instead run it from this repo.
Also:
- updates PR template
- a few comments are fixed
=> fix: run stale issues check under strategy matrix

docs/requirements.txt, docs/source/conf.py, docs/source/developers/code_of_conduct.rst
Use myst-parser instead of m2r2 for markdown files in docs. m2r2 is no longer maintained, see https://github.com/CrossNox/m2r2/issues/68
Todo:
=> docs: use myst-parser for markdown

.flake8, .github/workflows/python-flake8.yml, docs/source/conf.py
No longer maintaining Python 2.7 repos in LB. Also add linting for notebooks.
=> ci(python): update flake8 workflow

docs/source/conf.py
Update javascript sources, for https://github.com/daattali/beautiful-jekyll/pull/1375
=> docs(js): update javascript sources

.github/dependabot.yml, .github/workflows/common-lint.yml
Add cargo/rust support in preparation for maintaining a fork of pacman-repo-builder.
=> feat: add cargo support

.github/workflows/release-notifier.yml, .github/workflows/social-post.yml
- Drop support for posting to Facebook group (API no longer allows this)
- Move to LizardByte action afer repo was migrated from ReenigneArcher.
=> fix(notifier): update facebook post action

.github/workflows/release-notifier.yml
Jekyll blog posts need to be named like `YYYY-MM-DD-<anything>.md`. The previous code assumed the semver was separated by year, month, and day, but it is not.
=> fix(releases): properly name blog post files

SECURITY.md
These PR adds an href to the security tab of the current repo. We need to navigate up two directories or else GitHub resolves it to the blob url (which doesn't actually exist).
=> docs(security): add href for security tab

.github/workflows/codeql.yml
Discovered and fixed a bug when languages are duplicated (e.g. JavaScript and Typescript).
=> ci(codeql): ensure duplicate languages are not tested

.github/workflows/ci-docker.yml, .github/workflows/cla-gist-replicator.yml, .github/workflows/codeql.yml, .github/workflows/common-lint.yml, .github/workflows/global-replicator.yml, .github/workflows/issues-stale.yml, .github/workflows/issues.yml, .github/workflows/patch_missing_releases.yml, .github/workflows/release-notifier.yml, .github/workflows/renovate-config-validator.yml, .github/workflows/social-post.yml, .github/workflows/update-changelog.yml, .github/workflows/update-docs.yml
Add "actions" for CodeQL scanning.
Note: CodeQL flagged every workflow for not having "permissions" set explicitly. Hopefully none of the workflows break with what I have set, but might have a few surprises after the PRs are created in each repo.
- Resolves https://github.com/LizardByte/roadmap/issues/64
=> ci(codeql): enable for github actions

.github/workflows/ci-docker.yml
`setup-release-action` needs `write` permission.
For some reason the GITHUB_TOKEN cannot read repository metadata with `contents: read` even though the job indicates that it can read metadata. I guess that the keys needed are available only to users with elevated permissions.
=> ci(docker): increase permissions and bump release actions

.github/workflows/codeql.yml
This PR uses no build mode for codeql on the C++ analysis. See https://github.blog/changelog/2025-06-03-codeql-can-be-enabled-at-scale-on-c-c-repositories-in-public-preview-using-build-free-scanning/
See: https://github.com/LizardByte/Sunshine/pull/3943
=> ci(codeql): use no build mode

.github/workflows/__call-common-lint.yml
The current action is installing the `stable` toolchain, which while equivalent to the project toolchain they install components to separate locations which cannot be accessed correctly.
GitHub hosted runners now include rust, rustup and other rust tools so we can just invoke those directly.
=> fix(cargo-fmt): use project toolchain

.github/workflows/__call-common-lint.yml
- Use new setup-rust-toolchain action
=> fix(lint): use setup-rust-toolchain action

.github/workflows/__call-docker.yml
- Move update dockerhub readme to separate job
- Fix `BASE_TAG` env variable not being set
- Resolves https://github.com/LizardByte/roadmap/issues/91
=> fix(docker): move update dockerhub readme to separate job

.github/pull_request_template.md
This PR improves the PR template.
Key changes:
- Separate type of change options out according to conventional commit guidelines. This will make it easier to select the PR title for the squash and merge.
- Added a section for roadmap issues.
- Added comments to each section as well as the heading of the template.
- Added an "AI Usage" section to help maintainers gauge how heavily AI was used in the creation of the PR.
- Resolves https://github.com/LizardByte/roadmap/issues/96
=> chore(templates): update PR template

.github/matchers/clang-format.json, .github/matchers/cmake-lint.json, .github/matchers/gcc.json, .github/matchers/hadolint.json, .github/matchers/shellcheck-gcc.json, .github/matchers/yamllint.json, .github/workflows/__call-common-lint.yml, .github/workflows/__call-docker.yml, .github/workflows/__call-release-notifier.yml, .github/workflows/__call-update-docs.yml, .github/workflows/__call-update-flathub-repo.yml, .github/workflows/__call-update-pacman-repo.yml, .github/workflows/__renovate-config-validator.yml, .yamllint.yml
This PR adds actionlint which will run shellcheck against run sections in the workflows. Additionally, problem matchers have been added for the linters.
The yamllint action has been replaced with installed yamllint from pypi.
TODO:
For the future:
- Closes https://github.com/LizardByte/roadmap/issues/60
=> feat(workflows): add actionlint and PR annotations

.github/actionlint.yml, .github/workflows/__call-common-lint.yml
We need to add a custom config until the following are resolved:
- https://github.com/rhysd/actionlint/pull/542
- https://github.com/rhysd/actionlint/issues/533
=> fix(actionlint): add actionlint config file

.github/workflows/__call-release-notifier.yml, .github/workflows/__call-update-flathub-repo.yml, .github/workflows/__call-update-pacman-repo.yml, .github/workflows/_release-notifier.yml, .github/workflows/_update-flathub-repo.yml, .github/workflows/_update-pacman-repo.yml
Generated PRs were previously authored by the GitHub actor (typically myself), and committed by @github-actions[bot]. This change makes it so both of these will be done by our bot.
=> fix(workflows): generated PRs to be authored by LizardByte-bot

.github/workflows/__call-common-lint.yml
This PR adds the problem matcher for `nbqa flake8`. It failed previously due to a missing `=`, per https://github.com/gustavgransbo/flake8-github-annotations/issues/11#issuecomment-3173777107
TODO:
=> fix(common-lint): add problem matcher for nbqa flake8

CONTRIBUTING.md
- Adds more guidelines around AI usage, specially with regards to the PR body. Why does copilot generate PR bodies not using our template to begin with?
- Fix yamllint config file url.
- Update lint checks list.
- Closes https://github.com/LizardByte/.github/pull/504
=> docs(contributing): more ai updates

.github/workflows/__call-common-lint.yml
This PR checks trailing whitespace in text files as well as EOL statement in files.
=> feat(lint): check whitespace

.clang-format, .github/workflows/__call-common-lint.yml
When running clang-format on Windows, it would update all files because `LineEndings: LF` was specified. This PR removes the option from the config file, but we will re-inject it for the lint workflow to ensure files are not committed with Windows style line endings.
=> fix(lint): remove LineEnding from .clang-format config

.github/workflows/__update_license_years.yml
This PR adds a workflow to update the years in license file copyright messages, such as in MIT licenses.
=> feat(workflows): add license update workflow

.gitmodules, docs/source/developers/repository_standards.rst, docs/source/toc.rst
This PR adds a repository standards doc, and remove the `gitignore` submodule.
=> docs: add repository standards
